version: "3.5"
services:
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - db_network
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

  api:
    build:
      context: ./api/
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - "4000:4000"
    networks:
      - db_network
      - api_network
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    command: npm start
    stdin_open: true
    networks:
      - api_network

networks:
  db_network:
  api_network:

volumes:
  mongo-data:
